baseurl = "/"
languageCode = "it-IT"
languageLang = "it"
languageName = "Italian"
title = "Camerata Musicale Città di Arco"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["/img/logo-cameratamusicalecittadiarco.jpeg"]

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]

[markup.goldmark.parser]

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true